app1:
  replicas: 1
  image:
    repository: 487383300987.dkr.ecr.us-east-1.amazonaws.com/eks
    tag: latest
  service:
    type: ClusterIP
    port: 9000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
app2:
  replicas: 1
  image:
    repository: 487383300987.dkr.ecr.us-east-1.amazonaws.com/test
    tag: latest
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
ingress:
  host: "vj.klizos.com"
  certificateArn: "arn:aws:acm:us-east-1:487383300987:certificate/b6015ec9-a880-4011-ba14-e7175a40678b"