apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app2-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app2.service.type }}
  ports:
  - port: {{ .Values.app2.service.port }}
    targetPort: {{ .Values.app2.service.port }}
  selector:
    app: {{ .Release.Name }}-app2